project_id = "jsttoajuszshrivmgnmc"

[api]
enabled = true
port = 54321

[db]
port = 54322

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.abacatepay-webhook]
verify_jwt = false

[functions.hubla-webhook]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-auth-logs]
verify_jwt = false

[functions.get-db-logs]
verify_jwt = false

[functions.get-analytics-logs]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.createUserWithCredit]
verify_jwt = true

[functions.send-payment-confirmation]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.process-pending-paid-orders]
verify_jwt = false
