project_id = "jsttoajuszshrivmgnmc"

[api]
enabled = true
port = 54321

[db]
port = 54322

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.abacatepay-webhook]
verify_jwt = false

[functions.get-auth-logs]
verify_jwt = false

[functions.get-db-logs]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false