// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsttoajuszshrivmgnmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzdHRvYWp1c3pzaHJpdm1nbm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjM5MDAsImV4cCI6MjA3MjQ5OTkwMH0.NE-QETYb7j2kskV14gc6cu0KPLWRvS5ztpKIEkutJ10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});